### ISSUE TITLE
Missing contest data from leetcode.cn

### ISSUE THREAD

**Issue by BZH110** [SysSn13/leetcode-rating-predictor#53]
Contest data from leetcode.cn is missing for weekly-318

**Comment by gjygit** [comment]
* So, no one noticed the weekly-318？

**Comment by DaYangtuo247** [comment]
i have this problem too

**Comment by wine-fall** [comment]
yes, same on contest 319

**Comment by KargathEx** [comment]
I had the same problem for `weekly-318`  
for `contest-319` ,I found that I could search for my ranking within half an hour to a day after the game,and now,cannot.
So I'm guessing that it will delete some of the people's rankings after a day of competition, I'm not sure which ones.

**Comment by gdut-yy** [comment]
Same as weekly-contest-320.

**Comment by Isaachhh** [comment]
just changing the update frequency is fine.
the data fetched just after the contest ends is correct, but the data updated when around 1 hour after the contest does not include Leetcode.cn due to Leetcode's new design.
So keeping the origin data for longer time and updating it in the middle of week such as Tue. or Wed. will be fine.

**Comment by PARASnagpal99** [comment]
weekly contest 322 is missing .

**Comment by SysSn13** [comment]
this has been fixed now. We fetch the data from both leetcode.com & leetcode.cn servers now.
