### ISSUE TITLE
Clicking on FAQ does not expand it

### ISSUE THREAD

**Issue by SysSn13** [SysSn13/leetcode-rating-predictor#77]

**Comment by Strange-Quark-007** [comment]
Error in console

(index):4766 Uncaught TypeError: Cannot read properties of undefined (reading 'trim')
    at localizeDate ((index):4766:43)
    
 
![image](https://github.com/SysSn13/leetcode-rating-predictor/assets/110275359/dadc2149-21ee-4a59-a9fa-aab6b5b2e08f)

![image](https://github.com/SysSn13/leetcode-rating-predictor/assets/110275359/82d3a4e8-2732-4e20-ba2c-ae17cae95523)

When I run the other function manually in console, the accordions work

![image](https://github.com/SysSn13/leetcode-rating-predictor/assets/110275359/1a286f1c-86bf-4efd-a55c-430cf4fe1dd5)

 
 The typeError we get is due to fact that there is no .data property and so .trim() fails
 
 Fixed by changing .data to .textContent 
 
 
 Screenshot After fix 
 
![image](https://github.com/SysSn13/leetcode-rating-predictor/assets/110275359/60d7242d-0bb2-4725-96fc-64e108a330a4)
